name: i18n_checker
description: Command-line tool to improve the consistency of your various language files
version: 0.0.3
homepage: https://github.com/stevenosse/i18n_checker

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ">=0.3.0 <0.5.0"
  mason_logger: ^0.2.4
  path: ^1.8.3
  pub_updater: ^0.2.4

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: 1.0.3
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <6.0.0"


executables:
  i18n_checker:
